services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - ${PI_PORT}:80
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "America/Sao_Paulo"
      DNSMASQ_USER: "root"
    volumes:
      - "./data/etc-pihole:/etc/pihole"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
