services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - './data/etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
