services:  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - ${GF_PORT}:3000
    environment: 
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}

volumes:
  grafana_data:
    name: grafana_data