services:
  nginx:
    image: nginx:alpine
    container_name: nginx-redirect
    restart: unless-stopped
    ports:
      - "88:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
