services: 
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflared
    restart: unless-stopped 
    command: tunnel run 
    environment: 
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - henriqzimer

networks:
  henriqzimer:
    external: true