services: 
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflared
    restart: always 
    command: tunnel run 
    environment: 
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}