services: 
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflared
    dns:
      - 1.1.1.1
    restart: always 
    command: tunnel run 
    environment: 
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}